local areaOfEffectShapeType = {
    EMPTY = 32,
    CROSS_PLUS = 43,
    CROSS_SHARP = 35,
    CROSS_STAR_OMNIDIRECTIONAL = 42,
    LINE_SLASH = 47,
    CROSS_NO_DIAGONAL = 45,
    SEMI_COLUMN = 59,
    ENTIRE_MAP = 65,
    B = 66,
    LOZENGE_C = 67,
    CROSS_DIAGONAL = 68,
    FORK = 70,
    SQUARE = 71,
    LOZENGE_I = 73,
    LINE = 76,
    LOZENGE_O = 79,
    POINT = 80,
    CROSS_Q = 81,
    CROSS_ONLY_DIAGONAL = 84,
    HALF_LOZENGE = 85,
    CONE = 86,
    SQUARE_NO_DIAGONAL = 87,
    CROSS = 88,
    LOZENGE_ENTIRE_MAP = 97,
    Z = 90,
    LINE_STOPS_AT_TARGET = 108,
}

return areaOfEffectShapeType
