local spellCastResult = {
    CASTING_POSSIBLE = 0,
    LIMIT_OF_CASTS_PER_TURN_REACHED = 1,
    SPELL_ON_COOLDOWN = 2,
    INSUFICIENT_ACTION_POINTS = 3,
    LIMIT_OF_CAST_PER_TARGET_REACHED = 4,
    TARGET_TOO_FAR = 5,
    TARGET_TOO_CLOSE = 6,
    MUST_BE_CAST_IN_LINE = 7,
    TARGET_OUTSIDE_LINE_OF_SIGHT = 8,
    LIMIT_OF_SUMMONS_REACHED = 9,
    TARGET_CELL_IS_OCCUPIED = 10,
    TARGET_CELL_IS_EMPTY = 11,
    STATE_EFFECT_REQUIRED = 12,
    STATE_EFFECT_FORBIDDEN = 13,
    MUST_BE_CAST_IN_DIAGONAL = 14,
    UNKNOWN = 15,
    OUT_OF_RANGE = 16
}

return spellCastResult
